#!/usr/bin/env python3
"""Generate the compiled-in weights header for NNVertexFitExtrapolator from a
vertex-fit checkpoint (same numbers as the VFK1 blob, as constexpr arrays).

The header pattern follows the package precedent (FieldMapNNWeights.h in
Rec/Tr/TrackExtrapolators): weights ship with the code, no runtime file I/O,
and the tool's WeightsFile property becomes an optional override for studies.

Usage: vf_export_header.py <experiment_dir> <out_header.h>
"""
import json
import sys
from datetime import date
from pathlib import Path

import numpy as np
import torch

exp = Path(sys.argv[1])
out = Path(sys.argv[2])

ckpt = torch.load(exp / "best_model.pt", weights_only=False, map_location="cpu")
cfg = ckpt["config"]
assert cfg["model_type"] == "pinn_v2" and cfg.get("kick_scaled_head") \
    and cfg.get("z_features") and cfg.get("n_unroll", 1) == 1 \
    and cfg.get("kick_order", 1) == 1 and cfg["activation"] == "tanh"
h = cfg["hidden_dims"]
assert len(h) == 2 and h[0] == h[1]
H = h[0]

sd = ckpt["model_state_dict"]
norm = json.load(open(exp / "normalization.json"))
arrays = {
    "MEAN": np.asarray(norm["input_mean"], np.float32),
    "STD": np.asarray(norm["input_std"], np.float32),
    "W1": sd["encoder.0.weight"].numpy().astype(np.float32).ravel(),
    "B1": sd["encoder.0.bias"].numpy().astype(np.float32),
    "W2": sd["encoder.2.weight"].numpy().astype(np.float32).ravel(),
    "B2": sd["encoder.2.bias"].numpy().astype(np.float32),
    "W3": sd["correction_head.weight"].numpy().astype(np.float32).ravel(),
    "B3": sd["correction_head.bias"].numpy().astype(np.float32),
    "GAIN": np.exp(sd["kick_loggain"].numpy()).astype(np.float32),
}


def fmt(a):
    body = ", ".join(f"{v:.9g}f" for v in a)
    # wrap at ~100 chars
    lines, cur = [], "    "
    for tok in body.split(", "):
        if len(cur) + len(tok) > 96:
            lines.append(cur.rstrip())
            cur = "    "
        cur += tok + ", "
    lines.append(cur.rstrip().rstrip(","))
    return "\n".join(lines)


with open(out, "w") as f:
    f.write(f"""\
/*****************************************************************************\\
* (c) Copyright 2000-2026 CERN for the benefit of the LHCb Collaboration      *
*                                                                             *
* This software is distributed under the terms of the GNU General Public      *
* Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".   *
\\*****************************************************************************/
// Generated by track-extrapolation-pinn/deploy/vf_export_header.py on {date.today()}
// from experiment '{exp.name}' (best epoch {ckpt['epoch']}).
// The vertex-fit neural extrapolator weights (see NNVertexFitExtrapolator.cpp).
// Regenerate rather than edit.
#pragma once

namespace NNVertexFitWeights {{

  constexpr int H = {H};

""")
    for name, a in arrays.items():
        f.write(f"  constexpr float {name}[{len(a)}] = {{\n{fmt(a)} }};\n\n")
    f.write("} // namespace NNVertexFitWeights\n")
print(f"wrote {out} (H={H}, {out.stat().st_size} bytes) from {exp.name} epoch {ckpt['epoch']}")
